[build-system]
requires = ["setuptools>=61.0", "wheel>=0.38"]
build-backend = "setuptools.build_meta"

[project]
name = "ecs_cheques"
description = "Custom App For Cheques"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = []

[tool.bench.app]
modules = ["ecs_cheques"]
