[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "ecs_cheques"
description = "Custom App For Cheques"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = []

[tool.bench.app]
modules = ["ecs_cheques"]
